added smiles output
MehmetAzizYirik/MAYGEN pull request #44
Opened 2021-07-27 16:08 UTC by mSorok

There are two files that I modified: the main function, that now contains the possibility of adding SMILES output, and the POM file, as I needed some extra CDK libraries to do it.
Note that I could not create a pull request for the README! You just need to add to the README this line on your side in the "Usage" part:

` -type smiles                  Option to add if the output is to be in SMILES format. 
                               WARNING: this option slows down the total MAYGEN execution`

2021-07-28 05:51 UTC, javadev requested changes

2021-07-28 05:51 UTC, javadev commented on src/main/java/MAYGEN/MAYGEN.java
> +            if (cmd.hasOption("type")){
It will be better to support two formats.

It may be keys `-createSdf` and `-createSmiles`

2021-07-28 05:51 UTC, javadev commented on src/main/java/MAYGEN/MAYGEN.java
> +            }else if(writeSMILES){
Source codes may be formatted with help of maven plugin.

2021-08-06 13:55 UTC, javadev commented on src/main/java/MAYGEN/MAYGEN.java
> +            }else if(writeSMILES){
I added my pull request https://github.com/MehmetAzizYirik/MAYGEN/pull/47

2021-08-10 14:04 UTC, javadev commented
@mSorok we found that 

```
java -Xmx1G -jar MAYGEN-jar-with-dependencies.jar -f S150 -v -t -d file -os
```
causes NPE.

Please check.

2021-08-10 14:26 UTC, mSorok commented
Hum, I cannot reproduce the error as on my system, but I don't add the "-os" option.
Can you please paste the exact error (with the location)?

2021-08-10 14:31 UTC, javadev commented
@mSorok please use code from repository https://github.com/jscrdev/MAYGEN/tree/added-smiles-output

It was copied form your branch.

2021-08-10 14:33 UTC, mSorok commented
Again, I don't have any error, using this code (1 molecule generated, with SMILES). If you copy me the error you have, I might find out where is the problem

2021-08-10 14:38 UTC, javadev commented
I have screens

S150 causes null pointer for SMILES mode both in sequencial and parallel modes.

https://prnt.sc/1ma7u8y

For the SDF mode S150 works

https://prnt.sc/1ma8lwi

2021-08-10 14:40 UTC, javadev commented
It may because of mistake while copying your codes.

2021-08-10 14:42 UTC, mSorok commented
To what exactly corresponds the "-os" option? I cannot find it in the documentation

2021-08-10 14:46 UTC, javadev commented
```
usage: java -jar MAYGEN.jar -f <arg> [-v] [-t] [-d <arg>] [-m] [-os]

Generates molecular structures for a given molecular formula.
The input is a molecular formula string.

For example 'C2OH4'.

If user wants an output file, the directory is needed to be specified.
It is also possible to generate SMILES instead of an SDF file, but it will
slow down the generation time. For this, use the 'outputSMILES' option.

 -f,--formula <arg>   formula (required)
 -v,--verbose         print message
 -t,--tsvoutput       Output formula, number of structures and execution
                      time in CSV format
 -d,--filedir <arg>   Store output in given file
 -m,--multithread     Use multi thread
 -os,--outputSMILES   Store output in SMILES format in given file

Please report issues at https://github.com/MehmetAzizYirik/MAYGEN
```

2021-08-10 14:47 UTC, javadev commented
@mSorok you may clone repository with -os option and check it locally.

```
git clone -b added-smiles-output https://github.com/jscrdev/MAYGEN.git MAYGEN22
```

2021-08-10 15:11 UTC, mSorok commented
Ok, I realize that a lot of variable names changed between the moment I forked the code to write the SMILES function and this version of the code. Just copying the functions I wrote will not work, as I rely of global variable names (in particular on "symbolArray). I guess I will need to investigate the changes in the variable names and their content....

Also, maybe "-os" is not the most optimal short option name. Something like "-smi" would be better, and less confusing, no?

2021-08-11 03:25 UTC, javadev commented
@mSorok I analyzed Maria's repository. It generates the file with size 0.

https://prnt.sc/1mkrudn

but for SDF we have a file with size 14035 bytes

https://prnt.sc/1mksdvc

I suggest that Maria`s codes is not work with formula S150.

2021-08-16 16:41 UTC, closed without merging